config-version: 9
data-value-allowed-items: []
settings:
  baby-zombie-movement-speed: 0.5
  limit-player-interactions: true
effect-modifiers:
  strength: 1.3
  weakness: -0.5
stackable-buckets:
  lava: false
  water: false
  milk: false
warnWhenSettingExcessiveVelocity: true
world-settings:
  default:
    verbose: true
    generator-settings:
      canyon: false
      caves: false
      dungeon: false
      fortress: false
      mineshaft: false
      monument: false
      stronghold: false
      temple: false
      village: false
      flat-bedrock: false
    allow-block-location-tab-completion: true
    player-blocking-damage-multiplier: 0.5
    remove-invalid-mob-spawner-tile-entities: true
    optimize-explosions: false
    mob-spawner-tick-rate: 1
    cache-chunk-maps: true
    tnt-explosion-volume: 4.0
    disable-teleportation-suffocation-check: false
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    max-growth-height:
      cactus: 3
      reeds: 3
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 900
    player-exhaustion:
      block-break: 0.02500000037252903
      swimming: 0.014999999664723873
    despawn-ranges:
      soft: 32
      hard: 128
    falling-block-height-nerf: 0
    remove-unloaded:
      enderpearls: true
      tnt-entities: true
      falling-blocks: true
    game-mechanics:
      boats-drop-boats: false
      disable-player-crits: false
      disable-chest-cat-detection: false
      disable-end-credits: false
    nether-ceiling-void-damage: false
    load-chunks:
      enderpearls: false
      tnt-entities: false
      falling-blocks: false
    fast-drain:
      lava: false
      water: false
    lava-flow-speed:
      normal: 30
      nether: 10
    disable-explosion-knockback: false
    water-over-lava-flow-speed: 5
    fix-cannons: false
    tnt-entity-height-nerf: 0
    use-hopper-check: false
    all-chunks-are-slime-chunks: false
    allow-undead-horse-leashing: false
    container-update-tick-rate: 1
    keep-spawn-loaded: true
    portal-search-radius: 128
    disable-thunder: false
    disable-ice-and-snow: false
    tick-next-tick-list-cap: 10000
    tick-next-tick-list-cap-ignores-redstone: false
    falling-blocks-collide-with-signs: false
    disable-mood-sounds: false
    use-async-lighting: false
